#!/bin/sh

export DISPLAY=:0.0
#export XAUTHORITY=`ls -1t /home/user/.xauth* | head -1`
export DEVICE_NAME="Logitech USB Trackball"
export MIDDLE_BUTTON=2

DISPLAY=":0" /usr/bin/xinput set-prop \
   "$DEVICE_NAME" "ScrollMethod" button >&1
DISPLAY=":0" /usr/bin/xinput set-prop \
   "$DEVICE_NAME" "ScrollButton"  2 2>&1
DISPLAY=":0" /usr/bin/xinput set-button-map \
   "$DEVICE_NAME" 1 2 3 4 5 6 7 $MIDDLE_BUTTON $MIDDLE_BUTTON 2>&1

