#!/bin/sh

export DISPLAY=:0.0
#export XAUTHORITY=`ls -1t /home/user/.xauth* | head -1`

DISPLAY=":0" /usr/bin/xinput set-prop "Logitech USB Trackball" "ScrollMethod" button >&1
DISPLAY=":0" /usr/bin/xinput set-prop "Logitech USB Trackball" "ScrollButton"  2 2>&1
DISPLAY=":0" /usr/bin/xinput set-button-map "Logitech USB Trackball" 1 2 3 4 5 6 7 2 2 2>&1

