#!/bin/sh

TB_PATH="`realpath /tmp/trackball.lock`"
TB_DIRNAME="`dirname $TB_PATH`"

/usr/bin/inotifywait -m -e close_write --format "%w%f" "$TB_DIRNAME" \
| while read FILE; do
	if [[ `realpath "$FILE"` == "$TB_PATH" ]]; then
		echo "Running trackball script..."
		/usr/local/bin/trackball
	fi
done &

